### PR TITLE
Add smb2 patch

### PR DESCRIPTION
**Pull request by Mikanbu**

### CODE REVIEW

**Comment by tguillem** [comment]
Fine with me.

**Review by fkuehne — APPROVED** [review]
LGTM.

**Comment by carolanitz** [comment]
fine with me as well. @Mikanbu Did you try to use smb2 with a custom VLCKit build and verify that it works though?

**Comment by carolanitz** [comment]
This will also resolve https://code.videolan.org/videolan/vlc-ios/issues/342 with the next upcoming release

**Comment by Mikanbu** [comment]
@carolanitz Yes, tested on 3.0~

**Pull request merged**
