### PR TITLE
Bump MobileVLCKit and TVVLCKIT to 8.0 and 10.2 minimum deployment target

### PR DESCRIPTION
**Pull request by Mikanbu**
This fixes the MobileVLCKit nightly.

### CODE REVIEW

**Review by fkuehne — CHANGES_REQUESTED** [review]
Please bump to iOS 8.4 since this is what we actually require. For tvOS, 10.2 is good!

**Comment by Mikanbu** [comment]
Thank you for the review, I will make the change! Just out of curiosity should I bump to iOS 8.4 on 3.0 as well?

**Comment by fkuehne** [comment]
Yes, absolutely. We require 8.4 since the introduction of ChromeCast support (this is already reflected in the podspec).

**Comment by Mikanbu** [comment]
Oh I see, I will update the PR!

**Comment by fkuehne** [comment]
Feel free to directly push with those changes!

**Pull request merged**
