### PR TITLE
Add tvOS example

### PR DESCRIPTION
**Pull request by dcordero**
Just an example project integrating VLCKit into a tvOS application. It is also the first Swift example project.

### CODE REVIEW

**Comment by carolanitz** [comment]
hey that's a really great idea to add that! 
At first glance this looks amazing :) I need to check it out and run it when I find time!

**Review by fkuehne — APPROVED** [review]
Great work! Thanks a lot!

**Comment by carolanitz** [comment]
I tried running it today and ran into : 
```
/Users/caro/Documents/Projects/VLCKit/Examples/tvOS/SimplePlayback/SimplePlayback/SimplePlayback-Bridging-Header.h:1:9: error: 'TVVLCKit/TVVLCKit.h' file not found
#import <TVVLCKit/TVVLCKit.h>
        ^
1 error generated.
<unknown>:0: error: failed to emit precompiled header '/Users/caro/Library/Developer/Xcode/DerivedData/SimplePlayback-gnjuvyaaqnszuohfwkkpvpmxbiyc/Build/Intermediates.noindex/PrecompiledHeaders/SimplePlayback-Bridging-Header-swift_3E8GONYK5YKYG-clang_39CFHJB6Z4YZ1.pch' for bridging header '/Users/caro/Documents/Projects/VLCKit/Examples/tvOS/SimplePlayback/SimplePlayback/SimplePlayback-Bridging-Header.h'
```
any idea how to resolve this ?

**Comment by dcordero** [comment]
As the other examples, it requires building the library before. I will add a Podfile to the example project to make easier to launch.

**Comment by Mikanbu** [comment]
Hello~
Small question, do we need the `.xcworkspacedata` file? If not, should we add it to the `.gitignore`?

**Comment by dcordero** [comment]
tbh I am not really sure, but I have never seen the `xcworkspacedata` file ignored in an iOS project. I see that it is not ignored either in the [vlc-ios client .gitignore file](https://github.com/videolan/vlc-ios/blob/master/.gitignore) nor in the [.gitignore template](https://github.com/github/gitignore/blob/master/Objective-C.gitignore) of GitHub.

**Comment by mkchoi212** [comment]
This is completely irrelevant but @dcordero, I literally just did the same thing you did couple of minute ago 😆 https://github.com/videolan/vlckit/pull/14/commits/d9c139cf9fcf6d1d250fb75e3bc54a23d4c68245

**Comment by carolanitz** [comment]
This seems to be the most common .gitignore : https://github.com/github/gitignore/blob/master/Swift.gitignore 
and .xcworkspacedata is not part of it. So it should be checked in

**Comment by carolanitz** [comment]
tested it out and it works really well :) this was merged! Thank you again 🙌

**Pull request closed without merging**
