### PR TITLE
Project organization

### PR DESCRIPTION
**Pull request by mkchoi212**

### CODE REVIEW

**Review by carolanitz — APPROVED** [review]
looks good to me

**Comment by carolanitz** [comment]
@fkuehne are you okay with VLCMediaTests being deleted?

**Comment by carolanitz** [comment]
I guess @fkuehne  would've said something if it would not be okay for him since this was opened

merged with 13fc2d3ae5630f209561bc20e004ce1bfcbbd0ec

**Comment by fkuehne** [comment]
Yes, this was absolutely fine with me :)

**Pull request closed without merging**
